---
- name: Prepare variables
  ansible.builtin.include_tasks: prepare_variables.yml

- name: Create lab namespace for each user
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ item.key }}-lab"
  loop: "{{ _workload_user_data.users | dict2items }}"
  loop_control:
    label: "{{ item.key }}-lab"
  when: _workload_user_data.users is defined
