apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lab-4-4-default-deny
  labels:
    demo.redhat.com/name: ocp-troubleshooting-workshop
spec:
  podSelector:
    matchLabels:
      app: lab-4-4-backend
  policyTypes:
  - Ingress
