apiVersion: v1
kind: Service
metadata:
  name: acme-smf
  namespace: acme-5gc-edge
  labels:
    app: acme-smf
    app.kubernetes.io/name: acme-smf
    app.kubernetes.io/component: smf
    app.kubernetes.io/part-of: acme-5gc-edge-site
    demo.redhat.com/name: coo-incident-detection
    demo.redhat.com/created-by: agnosticd
spec:
  selector:
    app: acme-smf
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
