apiVersion: v1
kind: Service
metadata:
  name: acme-upf
  namespace: acme-5gc-edge
  labels:
    app: acme-upf
    app.kubernetes.io/name: acme-upf
    app.kubernetes.io/component: upf
    app.kubernetes.io/part-of: acme-5gc-edge-site
    demo.redhat.com/name: coo-incident-detection
    demo.redhat.com/created-by: agnosticd
spec:
  selector:
    app: acme-upf
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
