---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: perses-datasource
  namespace: acme-5gc-edge
  labels:
    demo.redhat.com/name: coo-incident-detection
    demo.redhat.com/created-by: agnosticd
---
apiVersion: v1
kind: Secret
metadata:
  name: perses-datasource-token
  namespace: acme-5gc-edge
  labels:
    demo.redhat.com/name: coo-incident-detection
    demo.redhat.com/created-by: agnosticd
  annotations:
    kubernetes.io/service-account.name: perses-datasource
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: perses-datasource-acme-5gc-edge-monitoring-view
  labels:
    demo.redhat.com/name: coo-incident-detection
    demo.redhat.com/created-by: agnosticd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
  - kind: ServiceAccount
    name: perses-datasource
    namespace: acme-5gc-edge
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: perses-dashboard-writer
  namespace: acme-5gc-edge
  labels:
    demo.redhat.com/name: coo-incident-detection
    demo.redhat.com/created-by: agnosticd
rules:
  - apiGroups: ["perses.dev"]
    resources: ["persesdashboards"]
    verbs: ["create", "update", "delete", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: perses-datasource-dashboard-writer
  namespace: acme-5gc-edge
  labels:
    demo.redhat.com/name: coo-incident-detection
    demo.redhat.com/created-by: agnosticd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: perses-dashboard-writer
subjects:
  - kind: ServiceAccount
    name: perses-datasource
    namespace: acme-5gc-edge
