apiVersion: perses.dev/v1alpha2
kind: PersesDatasource
metadata:
  name: thanos-querier
  namespace: acme-5gc-edge
  labels:
    demo.redhat.com/name: coo-incident-detection
    demo.redhat.com/created-by: agnosticd
spec:
  client:
    tls:
      caCert:
        certPath: /ca/service-ca.crt
        type: file
      enable: true
  config:
    default: true
    display:
      name: Thanos Queries
    plugin:
      kind: PrometheusDatasource
      spec:
        proxy:
          kind: HTTPProxy
          spec:
            secret: perses-datasource-token
            url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
