apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: logging
  labels:
    demo.redhat.com/name: coo-incident-detection
    demo.redhat.com/created-by: agnosticd
spec:
  type: Logging
  logging:
    lokiStack:
      name: logging-loki
      namespace: openshift-logging
