apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-netobserv-bucket
  namespace: openshift-logging
  labels:
    demo.redhat.com/name: coo-incident-detection
    demo.redhat.com/created-by: agnosticd
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: quay.io/minio/mc:latest
          command:
            - /bin/sh
            - -c
            - |
              export MC_CONFIG_DIR=/tmp/.mc
              mc alias set minio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
              mc mb --ignore-existing minio/netobserv
              echo "NetObserv bucket ready"
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_ROOT_PASSWORD
