apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: lab-4-1-route
  labels:
    app: lab-4-1-app
    demo.redhat.com/name: ocp-troubleshooting-workshop
spec:
  to:
    kind: Service
    name: lab-4-1-service
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
