apiVersion: v1
kind: Service
metadata:
  name: lab-4-1-service
  labels:
    app: lab-4-1-app
    demo.redhat.com/name: ocp-troubleshooting-workshop
spec:
  selector:
    app: myapp    # BUG: missing hyphen - should be "my-app"
  ports:
  - port: 8080
    targetPort: 8080
