apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: incident-simulator
  labels:
    app: worker
    app.kubernetes.io/name: worker
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: incident-simulator
    demo.redhat.com/name: coo-incident-detection
    demo.redhat.com/created-by: agnosticd
spec:
  selector:
    app: worker
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
