apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-6-1-app
  labels:
    app: lab-6-1-app
    demo.redhat.com/name: ocp-troubleshooting-workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-6-1-app
  template:
    metadata:
      labels:
        app: lab-6-1-app
    spec:
      containers:
      - name: web
        image: quay.io/redhat-telco-adoption/nginx-unprivileged:latest
        ports:
        - containerPort: 8080
        command: ["/usr/bin/nonexistent-binary"]
