apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-1-2-app
  labels:
    app: lab-1-2-app
    demo.redhat.com/name: ocp-troubleshooting-workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-1-2-app
  template:
    metadata:
      labels:
        app: lab-1-2-app
    spec:
      containers:
      - name: web
        image: quay.io/redhat-telco-adoption/nginx-unprivileged:latest
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: db-credentials
