apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
  labels:
    demo.redhat.com/name: coo-incident-detection
    demo.redhat.com/created-by: agnosticd
spec:
  serviceAccount:
    name: cluster-logging-operator
  outputs:
    - name: default-lokistack
      type: lokiStack
      lokiStack:
        target:
          name: logging-loki
          namespace: openshift-logging
        authentication:
          token:
            from: serviceAccount
      tls:
        ca:
          configMapName: openshift-service-ca.crt
          key: service-ca.crt
  pipelines:
    - name: application-logs
      inputRefs:
        - application
      outputRefs:
        - default-lokistack
    - name: infrastructure-logs
      inputRefs:
        - infrastructure
      outputRefs:
        - default-lokistack
    - name: audit-logs
      inputRefs:
        - audit
      outputRefs:
        - default-lokistack
