apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume-2-2
  labels:
    app: lab-2-2-app
    demo.redhat.com/name: ocp-troubleshooting-workshop
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: gold-storage
  resources:
    requests:
      storage: 1Gi
