apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: incident-simulator
  labels:
    app: backend-api
    app.kubernetes.io/name: backend-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: incident-simulator
    demo.redhat.com/name: coo-incident-detection
    demo.redhat.com/created-by: agnosticd
spec:
  selector:
    app: backend-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
