apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-6-3-app
  labels:
    app: lab-6-3-app
    demo.redhat.com/name: ocp-troubleshooting-workshop
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: lab-6-3-app
  template:
    metadata:
      labels:
        app: lab-6-3-app
    spec:
      containers:
      - name: web
        image: quay.io/redhat-telco-adoption/nginx-unprivileged:v99.99
        ports:
        - containerPort: 8080
